apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-app-ns
spec:
  type: LoadBalancer
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

