name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pylint httpx


      - name: Lint with pylint
        run: pylint fastapi-app/main.py

      - name: Run tests with pytest
        run: pytest fastapi-app/test_main.py

      - name: Build Docker image
        run: |
          docker build -f fastapi-app/Dockerfile -t ghcr.io/${{ github.repository }}/python-app/calculator:latest .
   
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/python-app/calculator:latest

      - name: Commit and push manifest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update image tag to $IMAGE_TAG"
            git push origin main
          fi

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
